version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3001:3200"
    #volumes:
    #  - .:/usr/app
    depends_on:
      - "postgres"
   # networks:
   #   - backend

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=dockercustomerdb
      - POSTGRES_PORT=5434
    ports:
      - 5434:5432


networks:
  default:
    external:
      name: infynetwork

